using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Velocity.Workflow.Generators;

[Generator]
public class DurableWorkflowGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateMethod(s),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(methodDeclarations, static (spc, method) => Execute(spc, method!));
    }

    private static bool IsCandidateMethod(SyntaxNode node)
    {
        return node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0;
    }

    private static IMethodSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var methodSyntax = (MethodDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(methodSyntax) is not IMethodSymbol symbol)
            return null;

        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name is "DurableWorkflowAttribute" or "DurableWorkflow")
            {
                return symbol;
            }
        }
        return null;
    }

    private static void Execute(SourceProductionContext context, IMethodSymbol methodSymbol)
    {
        var containingType = methodSymbol.ContainingType;
        var namespaceName = containingType.ContainingNamespace.ToDisplayString();
        var className = containingType.Name;
        var methodName = methodSymbol.Name;

        var generatedCode = $$"""
            // <auto-generated/>
            using System;
            using Velocity.Workflow.Core;

            namespace {{namespaceName}};

            public partial class {{className}}
            {
                /// <summary>
                /// Generated zero-allocation state machine runner for method '{{methodName}}'.
                /// </summary>
                public static unsafe int {{methodName}}_GeneratedRunner(ref DurableSlabHeader header)
                {
                    if (!header.IsValid) return -1;

                    // Execute step sequence via O(1) bitmask tracking
                    if (!header.IsStepSet(0))
                    {
                        header.BitmaskWord0 |= (1UL << 0);
                        header.CurrentStep = 1;
                    }

                    return (int)header.CurrentStep;
                }
            }
            """;

        context.AddSource($"{className}_{methodName}_Generated.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
    }
}
