using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Velocity.Workflow.Generators;

public static class StateMachineRewriter
{
    public static string GenerateRunnerClass(MethodDeclarationSyntax methodSyntax, string namespaceName, string className)
    {
        string methodName = methodSyntax.Identifier.ValueText;

        // Find all await expressions in the method body
        var awaitExpressions = methodSyntax.DescendantNodes()
            .OfType<AwaitExpressionSyntax>()
            .ToList();

        int stepCount = Math.Max(awaitExpressions.Count, 1);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Velocity.Workflow.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static unsafe int {methodName}_GeneratedRunner(ref DurableSlabHeader header)");
        sb.AppendLine("        {");
        sb.AppendLine($"            header.TotalSteps = {stepCount};");
        sb.AppendLine();

        for (int i = 0; i < stepCount; i++)
        {
            int word = i / 64;
            int bit = i % 64;
            ulong mask = 1UL << bit;

            sb.AppendLine($"            if (header.CurrentStep == {i})");
            sb.AppendLine("            {");
            switch (word)
            {
                case 0: sb.AppendLine($"                header.BitmaskWord0 |= 0x{mask:X}UL;"); break;
                case 1: sb.AppendLine($"                header.BitmaskWord1 |= 0x{mask:X}UL;"); break;
                case 2: sb.AppendLine($"                header.BitmaskWord2 |= 0x{mask:X}UL;"); break;
                case 3: sb.AppendLine($"                header.BitmaskWord3 |= 0x{mask:X}UL;"); break;
            }
            sb.AppendLine($"                header.CurrentStep = {i + 1};");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return (int)header.CurrentStep;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
