using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Velocity.Workflow.Generators;

/// <summary>
/// Rewrites a method's await expressions into a bitmask-driven state machine runner.
/// Each await point becomes a numbered step. On replay, completed steps are skipped
/// via the slab bitmask and cached results are returned from the workflow context.
///
/// Enhanced in Batch 35 with blittable struct packing:
///   - Analyzes local variables to compute memory layout
///   - Emits a [StructLayout(LayoutKind.Explicit)] state slab
///   - Includes bitmask delta tracking field
///   - Supports slot-based schema evolution via reserved padding
/// </summary>
public static class StateMachineRewriter
{
    /// <summary>
    /// Generate the full runner class with both the state machine runner
    /// and the blittable state slab struct.
    /// </summary>
    public static string GenerateRunnerClass(MethodDeclarationSyntax methodSyntax, string namespaceName, string className)
    {
        string methodName = methodSyntax.Identifier.ValueText;

        // Find all await expressions — each is a step boundary
        var awaitExpressions = methodSyntax.DescendantNodes()
            .OfType<AwaitExpressionSyntax>()
            .ToList();

        int stepCount = Math.Max(awaitExpressions.Count, 1);

        // Analyze local variables for blittable packing
        var localVars = AnalyzeLocalVariables(methodSyntax);

        // Compute struct layout
        var layout = ComputeBlittableLayout(localVars, stepCount);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Velocity.Workflow.Generators — Batch 35+ enhanced />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Velocity.Workflow.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // Emit the blittable state slab struct
        EmitBlittableSlab(sb, className, methodName, layout, stepCount);

        sb.AppendLine();

        // Emit the state machine runner
        EmitRunnerMethod(sb, className, methodName, awaitExpressions, stepCount);

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Analyze local variable declarations in the method to determine what needs
    /// to be packed into the blittable state slab.
    /// </summary>
    private static List<LocalVarInfo> AnalyzeLocalVariables(MethodDeclarationSyntax method)
    {
        var locals = new List<LocalVarInfo>();

        foreach (var statement in method.DescendantNodes().OfType<LocalDeclarationStatementSyntax>())
        {
            foreach (var variable in statement.Declaration.Variables)
            {
                string typeName = statement.Declaration.Type.ToString();
                string varName = variable.Identifier.ValueText;

                // Map C# types to blittable sizes
                int size = GetTypeSize(typeName);
                bool isBlittable = IsBlittableType(typeName);

                if (isBlittable)
                {
                    locals.Add(new LocalVarInfo(varName, typeName, size, isBlittable));
                }
            }
        }

        return locals;
    }

    /// <summary>
    /// Compute the memory layout for the blittable state slab.
    /// Fields are packed in descending size order (like a C compiler) for alignment.
    /// </summary>
    private static BlittableLayout ComputeBlittableLayout(List<LocalVarInfo> locals, int stepCount)
    {
        var layout = new BlittableLayout();

        // Sort by size descending for optimal packing (8-byte, 4-byte, 2-byte, 1-byte)
        var sorted = locals.OrderByDescending(l => l.Size).ToList();

        int offset = 0;

        // WorkflowId always at offset 0 (8 bytes)
        layout.Fields.Add(new FieldLayout("WorkflowId", "long", 8, 0));
        offset = 8;

        // Pack user variables
        foreach (var local in sorted)
        {
            // Align to natural boundary
            int alignment = Math.Min(local.Size, 8);
            if (offset % alignment != 0)
                offset += alignment - (offset % alignment);

            layout.Fields.Add(new FieldLayout(SanitizeFieldName(local.Name), local.TypeName, local.Size, offset));
            offset += local.Size;
        }

        // Bitmask for step tracking (4x u64 = 256 bits)
        int bitmaskAlignment = 32; // 256-bit bitmask needs 32-byte alignment
        if (offset % bitmaskAlignment != 0)
            offset += bitmaskAlignment - (offset % bitmaskAlignment);

        layout.Fields.Add(new FieldLayout("StepCompletionFlags", "Bitmask256", 32, offset));
        offset += 32;

        // Reserved padding for schema evolution (32 bytes as per vision)
        layout.Fields.Add(new FieldLayout("ReservedPadding", "byte[32]", 32, offset));
        offset += 32;

        layout.TotalSize = offset;
        // Round up to nearest 64-byte cache line
        if (layout.TotalSize % 64 != 0)
            layout.TotalSize += 64 - (layout.TotalSize % 64);

        return layout;
    }

    /// <summary>
    /// Emit the [StructLayout(LayoutKind.Explicit)] blittable state slab struct.
    /// </summary>
    private static void EmitBlittableSlab(StringBuilder sb, string className, string methodName,
        BlittableLayout layout, int stepCount)
    {
        string slabName = $"{className}_{methodName}_StateSlab";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Blittable state slab for '{methodName}'. {layout.TotalSize} bytes, {layout.Fields.Count} fields.");
        sb.AppendLine($"    /// Zero-copy memmap compatible — direct pointer cast for O(1) state resumption.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    [StructLayout(LayoutKind.Explicit, Size = {layout.TotalSize})]");
        sb.AppendLine($"    public struct {slabName}");
        sb.AppendLine("    {");

        foreach (var field in layout.Fields)
        {
            if (field.TypeName == "byte[32]")
            {
                // Reserved padding as individual bytes
                for (int i = 0; i < 32; i++)
                {
                    sb.AppendLine($"        [FieldOffset({field.Offset + i})] public byte Reserved_{i};");
                }
            }
            else if (field.TypeName == "Bitmask256")
            {
                // Bitmask256 = 4x ulong
                sb.AppendLine($"        [FieldOffset({field.Offset})] public ulong Bitmask_Word0;");
                sb.AppendLine($"        [FieldOffset({field.Offset + 8})] public ulong Bitmask_Word1;");
                sb.AppendLine($"        [FieldOffset({field.Offset + 16})] public ulong Bitmask_Word2;");
                sb.AppendLine($"        [FieldOffset({field.Offset + 24})] public ulong Bitmask_Word3;");
            }
            else
            {
                sb.AppendLine($"        [FieldOffset({field.Offset})] public {field.TypeName} {field.Name};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>Check if a step bit is set in the bitmask.</summary>");
        sb.AppendLine("        public bool IsStepCompleted(int step)");
        sb.AppendLine("        {");
        sb.AppendLine("            int word = step / 64;");
        sb.AppendLine("            ulong bit = 1UL << (step % 64);");
        sb.AppendLine("            return word switch");
        sb.AppendLine("            {");
        sb.AppendLine("                0 => (Bitmask_Word0 & bit) != 0,");
        sb.AppendLine("                1 => (Bitmask_Word1 & bit) != 0,");
        sb.AppendLine("                2 => (Bitmask_Word2 & bit) != 0,");
        sb.AppendLine("                3 => (Bitmask_Word3 & bit) != 0,");
        sb.AppendLine("                _ => false,");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Set a step completion bit in the bitmask.</summary>");
        sb.AppendLine("        public void MarkStepCompleted(int step)");
        sb.AppendLine("        {");
        sb.AppendLine("            int word = step / 64;");
        sb.AppendLine("            ulong bit = 1UL << (step % 64);");
        sb.AppendLine("            switch (word)");
        sb.AppendLine("            {");
        sb.AppendLine("                case 0: Bitmask_Word0 |= bit; break;");
        sb.AppendLine("                case 1: Bitmask_Word1 |= bit; break;");
        sb.AppendLine("                case 2: Bitmask_Word2 |= bit; break;");
        sb.AppendLine("                case 3: Bitmask_Word3 |= bit; break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Emit the bitmask-driven state machine runner method.
    /// </summary>
    private static void EmitRunnerMethod(StringBuilder sb, string className, string methodName,
        List<AwaitExpressionSyntax> awaitExpressions, int stepCount)
    {
        string slabName = $"{className}_{methodName}_StateSlab";

        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Generated zero-allocation state machine runner for '{methodName}'.");
        sb.AppendLine($"        /// Steps: {stepCount}. Uses slab bitmask for O(1) replay detection.");
        sb.AppendLine($"        /// Blittable slab enables zero-copy state resumption via pointer cast.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static async Task<object?> {methodName}_GeneratedRunner(WorkflowContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var totalSteps = {stepCount};");
        sb.AppendLine();

        for (int i = 0; i < stepCount; i++)
        {
            var awaitExpr = i < awaitExpressions.Count ? awaitExpressions[i] : null;
            string activityName = ExtractActivityName(awaitExpr, i);
            string argsCode = ExtractArguments(awaitExpr);

            sb.AppendLine($"            // Step {i}: {activityName}");
            sb.AppendLine($"            if (!ctx.IsStepCompleted({i}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                var result_{i} = await ctx.ExecuteStepAsync({i}, \"{activityName}\"{argsCode});");
            sb.AppendLine($"                return result_{i}; // Suspend — activity scheduled, will resume on completion");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            // All steps completed");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string SanitizeFieldName(string name) =>
        new string(name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    private static int GetTypeSize(string typeName) => typeName switch
    {
        "long" or "ulong" or "double" => 8,
        "int" or "uint" or "float" => 4,
        "short" or "ushort" => 2,
        "byte" or "sbyte" or "bool" => 1,
        "decimal" => 16,
        "DateTime" => 8,
        _ => 8 // default to pointer-sized
    };

    private static bool IsBlittableType(string typeName) => typeName switch
    {
        "long" or "ulong" or "int" or "uint" or "short" or "ushort" or
        "byte" or "sbyte" or "float" or "double" or "decimal" or "bool" or
        "DateTime" => true,
        _ => false
    };

    /// <summary>
    /// Extract the activity/method name from an await expression.
    /// </summary>
    private static string ExtractActivityName(AwaitExpressionSyntax? awaitExpr, int fallbackIndex)
    {
        if (awaitExpr is null) return $"Step_{fallbackIndex}";

        var expression = awaitExpr.Expression;

        if (expression is InvocationExpressionSyntax invocation)
        {
            if (invocation.Expression is IdentifierNameSyntax identifier)
                return identifier.Identifier.ValueText;
            if (invocation.Expression is MemberAccessExpressionSyntax memberAccess)
                return memberAccess.Name.Identifier.ValueText;
        }

        if (expression is IdentifierNameSyntax id)
            return id.Identifier.ValueText;

        return $"Step_{fallbackIndex}";
    }

    /// <summary>
    /// Extract argument expressions from an await invocation.
    /// </summary>
    private static string ExtractArguments(AwaitExpressionSyntax? awaitExpr)
    {
        if (awaitExpr is null) return "";

        if (awaitExpr.Expression is InvocationExpressionSyntax invocation && invocation.ArgumentList.Arguments.Count > 0)
        {
            var args = invocation.ArgumentList.Arguments;
            var argStrings = args.Select(a => a.Expression.ToString());
            return ", new object?[] { " + string.Join(", ", argStrings) + " }";
        }

        return "";
    }

    // Layout analysis types
    private class LocalVarInfo
    {
        public string Name { get; }
        public string TypeName { get; }
        public int Size { get; }
        public bool IsBlittable { get; }
        public LocalVarInfo(string name, string typeName, int size, bool isBlittable)
        {
            Name = name; TypeName = typeName; Size = size; IsBlittable = isBlittable;
        }
    }

    private class BlittableLayout
    {
        public List<FieldLayout> Fields { get; } = new();
        public int TotalSize { get; set; }
    }

    private class FieldLayout
    {
        public string Name { get; }
        public string TypeName { get; }
        public int Size { get; }
        public int Offset { get; }
        public FieldLayout(string name, string typeName, int size, int offset)
        {
            Name = name; TypeName = typeName; Size = size; Offset = offset;
        }
    }
}
