apiVersion: v1
kind: Namespace
metadata:
  name: velocity-system
  labels:
    app.kubernetes.io/part-of: velocity
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
