plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'io.velocity.sdk'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    api 'io.grpc:grpc-netty-shaded:1.62.2'
    api 'io.grpc:grpc-protobuf:1.62.2'
    api 'io.grpc:grpc-stub:1.62.2'
    api 'com.google.protobuf:protobuf-java:3.25.3'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.3'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.62.2'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir '../../src/Velocity.Workflow.Server/Protos'
        }
    }
}

test {
    useJUnitPlatform()
}
