//! History shard management — shard ownership, mutable state, state reconstruction.
//! Manages history shards with lease-based ownership, mutable state tracking with
//! optimistic concurrency, and state reconstruction from event history replay.
//! Mirrors Temporal's history shard management.

use std::collections::{HashMap, VecDeque};
use std::sync::{Mutex, RwLock};
use std::time::Instant;

use crate::engine::WorkflowStatus;

// ─── Mutable State ───────────────────────────────────────────────────────────

/// Mutable state for a single workflow execution within a shard.
/// Tracks the current state with optimistic concurrency control.
#[derive(Debug, Clone)]
pub struct MutableState {
    pub workflow_key: u64,
    pub workflow_id: u64,
    pub run_id: u64,
    pub status: WorkflowStatus,
    pub next_event_id: u64,
    pub last_first_event_id: u64,
    pub generation: u64, // optimistic concurrency counter
    pub pending_signals: VecDeque<String>,
    pub pending_queries: VecDeque<String>,
    pub pending_updates: VecDeque<String>,
    pub pending_children: Vec<u64>,
    pub is_terminal: bool,
}

impl MutableState {
    pub fn new(workflow_key: u64, workflow_id: u64, run_id: u64) -> Self {
        Self {
            workflow_key,
            workflow_id,
            run_id,
            status: WorkflowStatus::Running,
            next_event_id: 1,
            last_first_event_id: 0,
            generation: 0,
            pending_signals: VecDeque::new(),
            pending_queries: VecDeque::new(),
            pending_updates: VecDeque::new(),
            pending_children: Vec::new(),
            is_terminal: false,
        }
    }

    /// Allocate the next event ID.
    pub fn allocate_event_id(&mut self) -> u64 {
        let id = self.next_event_id;
        self.next_event_id += 1;
        id
    }

    /// Transition to a terminal state.
    pub fn transition_to_terminal(&mut self, status: WorkflowStatus) -> bool {
        if self.is_terminal {
            return false;
        }
        self.status = status;
        self.is_terminal = true;
        self.generation += 1;
        true
    }

    /// Check if the workflow is in a terminal state.
    pub fn check_terminal(&self) -> bool {
        matches!(
            self.status,
            WorkflowStatus::Completed
                | WorkflowStatus::Failed
                | WorkflowStatus::Canceled
                | WorkflowStatus::Terminated
                | WorkflowStatus::ContinuedAsNew
        )
    }

    /// Add a pending signal.
    pub fn add_signal(&mut self, signal_name: String) {
        self.pending_signals.push_back(signal_name);
    }

    /// Drain pending signals.
    pub fn drain_signals(&mut self, count: usize) -> Vec<String> {
        let n = count.min(self.pending_signals.len());
        self.pending_signals.drain(..n).collect()
    }

    /// Add a pending child workflow.
    pub fn add_child(&mut self, child_key: u64) {
        self.pending_children.push(child_key);
    }

    /// Remove a completed child workflow.
    pub fn remove_child(&mut self, child_key: u64) -> bool {
        if let Some(pos) = self.pending_children.iter().position(|&k| k == child_key) {
            self.pending_children.remove(pos);
            true
        } else {
            false
        }
    }
}

// ─── Shard Ownership ─────────────────────────────────────────────────────────

/// State of a shard.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShardState {
    Available,
    Owned,
    Transferring,
}

/// Ownership info for a shard.
#[derive(Debug, Clone)]
pub struct ShardOwnership {
    pub shard_id: u64,
    pub owner_host: String,
    pub lease_expiry_ms: u64,
    pub state: ShardState,
    pub generation: u64,
}

/// Statistics for a shard.
#[derive(Debug, Clone, Default)]
pub struct ShardStats {
    pub workflow_count: u64,
    pub pending_transfer_tasks: u64,
    pub replication_lag: u64,
}

// ─── Transfer Task ───────────────────────────────────────────────────────────

/// Kind of transfer task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransferTaskKind {
    ActivityTask,
    WorkflowTask,
    CloseExecution,
    CancelExecution,
    StartChildExecution,
    DeleteExecution,
}

/// A transfer task generated by state transitions.
#[derive(Debug, Clone)]
pub struct TransferTask {
    pub task_id: u64,
    pub workflow_key: u64,
    pub kind: TransferTaskKind,
    pub target_queue: String,
    pub created_at: Instant,
    pub retry_count: u32,
}

// ─── Shard Context ───────────────────────────────────────────────────────────

/// Context for a single history shard. Manages mutable states and transfer tasks.
pub struct ShardContext {
    shard_id: u64,
    states: RwLock<HashMap<u64, MutableState>>,
    transfer_tasks: Mutex<VecDeque<TransferTask>>,
    next_task_id: std::sync::atomic::AtomicU64,
    ownership: RwLock<ShardOwnership>,
    stats: RwLock<ShardStats>,
}

impl ShardContext {
    pub fn new(shard_id: u64, owner_host: &str) -> Self {
        Self {
            shard_id,
            states: RwLock::new(HashMap::new()),
            transfer_tasks: Mutex::new(VecDeque::new()),
            next_task_id: std::sync::atomic::AtomicU64::new(1),
            ownership: RwLock::new(ShardOwnership {
                shard_id,
                owner_host: owner_host.to_string(),
                lease_expiry_ms: 0,
                state: ShardState::Owned,
                generation: 0,
            }),
            stats: RwLock::new(ShardStats::default()),
        }
    }

    /// Get or create mutable state for a workflow.
    pub fn get_or_create_state(
        &self,
        workflow_key: u64,
        workflow_id: u64,
        run_id: u64,
    ) -> MutableState {
        let mut states = self.states.write().unwrap();
        let is_new = !states.contains_key(&workflow_key);
        let state = states
            .entry(workflow_key)
            .or_insert_with(|| MutableState::new(workflow_key, workflow_id, run_id))
            .clone();
        if is_new {
            self.stats.write().unwrap().workflow_count += 1;
        }
        state
    }

    /// Update mutable state with optimistic concurrency check.
    pub fn update_state(&self, state: MutableState) -> Result<(), String> {
        let mut states = self.states.write().unwrap();
        if let Some(existing) = states.get(&state.workflow_key) {
            if existing.generation != state.generation {
                return Err(format!(
                    "concurrent modification: expected generation {}, got {}",
                    existing.generation, state.generation
                ));
            }
        }
        let mut updated = state;
        updated.generation += 1;
        states.insert(updated.workflow_key, updated);
        Ok(())
    }

    /// Remove mutable state for a workflow.
    pub fn remove_state(&self, workflow_key: u64) -> bool {
        let removed = self.states.write().unwrap().remove(&workflow_key).is_some();
        if removed {
            let mut stats = self.stats.write().unwrap();
            stats.workflow_count = stats.workflow_count.saturating_sub(1);
        }
        removed
    }

    /// Get mutable state for a workflow.
    pub fn get_state(&self, workflow_key: u64) -> Option<MutableState> {
        self.states.read().unwrap().get(&workflow_key).cloned()
    }

    /// Enqueue a transfer task.
    pub fn enqueue_transfer(
        &self,
        workflow_key: u64,
        kind: TransferTaskKind,
        target_queue: &str,
    ) -> u64 {
        let task_id = self
            .next_task_id
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let task = TransferTask {
            task_id,
            workflow_key,
            kind,
            target_queue: target_queue.to_string(),
            created_at: Instant::now(),
            retry_count: 0,
        };
        self.transfer_tasks.lock().unwrap().push_back(task);
        self.stats.write().unwrap().pending_transfer_tasks += 1;
        task_id
    }

    /// Dequeue transfer tasks.
    pub fn dequeue_transfers(&self, max_count: usize) -> Vec<TransferTask> {
        let mut tasks = self.transfer_tasks.lock().unwrap();
        let count = max_count.min(tasks.len());
        let result: Vec<TransferTask> = tasks.drain(..count).collect();
        self.stats.write().unwrap().pending_transfer_tasks = tasks.len() as u64;
        result
    }

    /// Get the number of pending transfer tasks.
    pub fn pending_transfer_count(&self) -> usize {
        self.transfer_tasks.lock().unwrap().len()
    }

    /// Get shard ownership info.
    pub fn ownership(&self) -> ShardOwnership {
        self.ownership.read().unwrap().clone()
    }

    /// Get shard statistics.
    pub fn stats(&self) -> ShardStats {
        self.stats.read().unwrap().clone()
    }

    /// Get the shard ID.
    pub fn shard_id(&self) -> u64 {
        self.shard_id
    }

    /// Reconstruct mutable state from a sequence of event types.
    /// Replays events to rebuild state.
    pub fn reconstruct_state(
        &self,
        workflow_key: u64,
        events: &[(u64, u8)],
    ) -> Option<MutableState> {
        let states = self.states.read().unwrap();
        let existing = states.get(&workflow_key);
        let workflow_id = existing.map(|s| s.workflow_id).unwrap_or(0);
        let run_id = existing.map(|s| s.run_id).unwrap_or(0);
        drop(states);

        let mut state = MutableState::new(workflow_key, workflow_id, run_id);
        for (event_id, event_type) in events {
            state.allocate_event_id();
            state.last_first_event_id = *event_id;
            // Apply terminal transitions
            match event_type {
                3 => {
                    state.transition_to_terminal(WorkflowStatus::Completed);
                }
                4 => {
                    state.transition_to_terminal(WorkflowStatus::Failed);
                }
                5 => {
                    state.transition_to_terminal(WorkflowStatus::Canceled);
                }
                6 => {
                    state.transition_to_terminal(WorkflowStatus::Terminated);
                }
                7 => {
                    state.transition_to_terminal(WorkflowStatus::ContinuedAsNew);
                }
                _ => {}
            }
        }
        state.generation = 0;
        Some(state)
    }
}

// ─── History Shard Manager ───────────────────────────────────────────────────

/// Manages multiple history shards with lease-based ownership.
pub struct HistoryShardManager {
    shards: RwLock<HashMap<u64, ShardContext>>,
    num_shards: u64,
    owner_host: String,
}

impl HistoryShardManager {
    pub fn new(num_shards: u64, owner_host: &str) -> Self {
        Self {
            shards: RwLock::new(HashMap::new()),
            num_shards,
            owner_host: owner_host.to_string(),
        }
    }

    /// Get or create a shard context.
    pub fn get_shard(&self, shard_id: u64) -> ShardContext {
        // Check if already exists
        {
            let shards = self.shards.read().unwrap();
            if let Some(ctx) = shards.get(&shard_id) {
                return ShardContext::new(ctx.shard_id(), &self.owner_host);
            }
        }
        // Create new
        let mut shards = self.shards.write().unwrap();
        let ctx = ShardContext::new(shard_id, &self.owner_host);
        shards.insert(shard_id, ShardContext::new(shard_id, &self.owner_host));
        ctx
    }

    /// Determine which shard a workflow belongs to.
    pub fn shard_for_workflow(&self, workflow_key: u64) -> u64 {
        workflow_key % self.num_shards
    }

    /// Get the number of managed shards.
    pub fn shard_count(&self) -> u64 {
        self.num_shards
    }

    /// Get the owner host.
    pub fn owner_host(&self) -> &str {
        &self.owner_host
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mutable_state_event_allocation() {
        let mut state = MutableState::new(1, 100, 200);
        assert_eq!(state.allocate_event_id(), 1);
        assert_eq!(state.allocate_event_id(), 2);
        assert_eq!(state.allocate_event_id(), 3);
        assert_eq!(state.next_event_id, 4);
    }

    #[test]
    fn test_mutable_state_terminal_transition() {
        let mut state = MutableState::new(1, 100, 200);
        assert!(!state.is_terminal);
        assert!(state.transition_to_terminal(WorkflowStatus::Completed));
        assert!(state.is_terminal);
        assert_eq!(state.status, WorkflowStatus::Completed);
        // Second transition should fail
        assert!(!state.transition_to_terminal(WorkflowStatus::Failed));
    }

    #[test]
    fn test_mutable_state_signals() {
        let mut state = MutableState::new(1, 100, 200);
        state.add_signal("sig1".into());
        state.add_signal("sig2".into());
        state.add_signal("sig3".into());

        let drained = state.drain_signals(2);
        assert_eq!(drained.len(), 2);
        assert_eq!(drained[0], "sig1");
        assert_eq!(state.pending_signals.len(), 1);
    }

    #[test]
    fn test_mutable_state_children() {
        let mut state = MutableState::new(1, 100, 200);
        state.add_child(10);
        state.add_child(20);
        assert_eq!(state.pending_children.len(), 2);

        assert!(state.remove_child(10));
        assert_eq!(state.pending_children.len(), 1);
        assert!(!state.remove_child(99));
    }

    #[test]
    fn test_shard_context_state_crud() {
        let ctx = ShardContext::new(0, "host-a");
        let state = ctx.get_or_create_state(42, 100, 200);
        assert_eq!(state.workflow_key, 42);
        assert_eq!(state.status, WorkflowStatus::Running);

        let fetched = ctx.get_state(42).unwrap();
        assert_eq!(fetched.workflow_key, 42);

        assert!(ctx.remove_state(42));
        assert!(ctx.get_state(42).is_none());
    }

    #[test]
    fn test_shard_context_optimistic_concurrency() {
        let ctx = ShardContext::new(0, "host-a");
        let mut state = ctx.get_or_create_state(42, 100, 200);

        // Update with correct generation
        assert!(ctx.update_state(state.clone()).is_ok());

        // Update with stale generation should fail
        state.generation = 0; // stale
        assert!(ctx.update_state(state).is_err());
    }

    #[test]
    fn test_shard_context_transfer_tasks() {
        let ctx = ShardContext::new(0, "host-a");
        ctx.enqueue_transfer(42, TransferTaskKind::ActivityTask, "activity-queue");
        ctx.enqueue_transfer(43, TransferTaskKind::WorkflowTask, "workflow-queue");

        assert_eq!(ctx.pending_transfer_count(), 2);

        let tasks = ctx.dequeue_transfers(10);
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].workflow_key, 42);
        assert_eq!(ctx.pending_transfer_count(), 0);
    }

    #[test]
    fn test_shard_context_reconstruct_state() {
        let ctx = ShardContext::new(0, "host-a");
        ctx.get_or_create_state(42, 100, 200);

        let events = vec![
            (1, 1), // WorkflowExecutionStarted
            (2, 2), // WorkflowTaskScheduled
            (3, 3), // WorkflowExecutionCompleted
        ];

        let state = ctx.reconstruct_state(42, &events).unwrap();
        assert!(state.is_terminal);
        assert_eq!(state.status, WorkflowStatus::Completed);
    }

    #[test]
    fn test_history_shard_manager() {
        let mgr = HistoryShardManager::new(16, "host-a");
        assert_eq!(mgr.shard_count(), 16);
        assert_eq!(mgr.owner_host(), "host-a");

        let shard_id = mgr.shard_for_workflow(42);
        assert_eq!(shard_id, 42 % 16);
    }

    #[test]
    fn test_shard_stats() {
        let ctx = ShardContext::new(0, "host-a");
        ctx.get_or_create_state(1, 10, 20);
        ctx.get_or_create_state(2, 11, 21);
        ctx.enqueue_transfer(1, TransferTaskKind::ActivityTask, "q");

        let stats = ctx.stats();
        assert_eq!(stats.workflow_count, 2);
        assert_eq!(stats.pending_transfer_tasks, 1);
    }
}
