#!/bin/bash
echo "=== Checking Temporal VM ==="
echo "Docker containers:"
docker ps 2>/dev/null || echo "Docker not running"
echo "---"
echo "Production dir:"
ls ~/temporal-production/ 2>/dev/null || echo "No production dir"
echo "---"
echo "Service health:"
curl -s --max-time 3 http://localhost:8080/health 2>/dev/null || echo "No service on 8080"
echo "---"
echo "Temporal gRPC port:"
python3 -c "import socket; s=socket.socket(); s.settimeout(2); s.connect(('localhost',7233)); print('PORT_OK'); s.close()" 2>/dev/null || echo "PORT_7233_CLOSED"
echo "---"
echo "Python packages:"
pip3 list 2>/dev/null | grep -iE "temporal|fastapi|uvicorn" || echo "No relevant packages"
echo "---"
echo "Running processes:"
ps aux | grep -E "service.py|temporal" | grep -v grep || echo "No relevant processes"
