#!/bin/bash
echo "=== Checking DBOS VM ==="
echo "Production dir:"
ls ~/dbos-production/ 2>/dev/null || echo "No production dir"
echo "---"
echo "PostgreSQL:"
systemctl is-active postgresql 2>/dev/null || echo "PG not active"
sudo -u postgres psql -c "SELECT 1" 2>/dev/null || echo "Cannot connect to PG"
echo "---"
echo "Service health:"
curl -s --max-time 3 http://localhost:8080/health 2>/dev/null || echo "No service on 8080"
echo "---"
echo "Python packages:"
pip3 list 2>/dev/null | grep -iE "dbos|fastapi|uvicorn|psycopg" || echo "No relevant packages"
echo "---"
echo "Running processes:"
ps aux | grep -E "service.py|dbos" | grep -v grep || echo "No relevant processes"
