#!/bin/bash
echo "=== Checking Restate VM ==="
echo "Docker containers:"
docker ps 2>/dev/null || echo "Docker not running"
echo "---"
echo "Production dir:"
ls ~/restate-production/ 2>/dev/null || echo "No production dir"
echo "---"
echo "Restate service discovery:"
curl -s --max-time 3 http://localhost:9080/restate/discover 2>/dev/null || echo "No service on 9080"
echo "---"
echo "Restate ingress:"
curl -s --max-time 3 http://localhost:8082/ 2>/dev/null || echo "No ingress on 8082"
echo "---"
echo "Node packages:"
ls ~/restate-production/node_modules/@restate/sdk 2>/dev/null && echo "SDK installed" || echo "SDK not installed"
echo "---"
echo "Running processes:"
ps aux | grep -E "service.js|restate" | grep -v grep || echo "No relevant processes"
