{{- if .Values.monitoring.prometheus.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "velocity.fullname" . }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    {{- with .Values.monitoring.prometheus.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "velocity.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: health
      path: {{ .Values.monitoring.prometheus.podMonitor.metricsPath | default "/metrics" }}
      interval: {{ .Values.monitoring.prometheus.podMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.prometheus.podMonitor.scrapeTimeout | default "10s" }}
      {{- if or .Values.metrics.existingSecret .Values.metrics.token }}
      authorization:
        credentials:
          name: {{ .Values.metrics.existingSecret | default (include "velocity.fullname" .) }}
          key: token
      {{- end }}
      {{- if .Values.monitoring.prometheus.podMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.monitoring.prometheus.podMonitor.relabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
