{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velocity.postgresSecretName" . }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  connection-string: {{ printf "Host=%s;Port=%d;Database=%s;Username=%s;Password=%s" (default (printf "%s-postgresql" (include "velocity.fullname" .)) .Values.postgresql.host) (int .Values.postgresql.port) .Values.postgresql.auth.database .Values.postgresql.auth.username .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velocity.fullname" . }}-auth
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.jwtIssuer }}
  jwt-issuer: {{ .Values.auth.jwtIssuer | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.jwtAudience }}
  jwt-audience: {{ .Values.auth.jwtAudience | b64enc | quote }}
  {{- end }}
