{{- if and .Values.metrics.token (not .Values.metrics.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velocity.fullname" . }}-metrics-token
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.metrics.token | b64enc | quote }}
{{- end }}
