{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "velocity.fullname" . }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ include "velocity.fullname" . }}
  selector:
    matchLabels:
      {{- include "velocity.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: health
      path: {{ .Values.serviceMonitor.metricsPath | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
      {{- if or .Values.metrics.existingSecret .Values.metrics.token }}
      authorization:
        credentials:
          {{- if .Values.metrics.existingSecret }}
          name: {{ .Values.metrics.existingSecret }}
          {{- else }}
          name: {{ include "velocity.fullname" . }}-metrics-token
          {{- end }}
          key: token
      {{- end }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
