{{- if and .Values.tls.enabled .Values.tls.certManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "velocity.fullname" . }}-tls
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName | default (printf "%s-tls" (include "velocity.fullname" .)) }}
  duration: {{ .Values.tls.duration | default "2160h" }}
  renewBefore: {{ .Values.tls.renewBefore | default "360h" }}
  commonName: {{ .Values.tls.commonName | quote }}
  dnsNames:
    - {{ .Values.tls.commonName | quote }}
    - {{ printf "%s.%s.svc.cluster.local" (include "velocity.fullname" .) .Release.Namespace | quote }}
  issuerRef:
    name: {{ .Values.tls.issuerRef.name | quote }}
    kind: {{ .Values.tls.issuerRef.kind | default "ClusterIssuer" }}
{{- end }}
